2: catch( AssertionError e ) {
3: catch( AssertionError e ) { error = null ;
3: catch( AssertionError e ) { error = e ;
3: catch( AssertionError e ) { error = error ;
3: catch( final AssertionError e ) {
6: catch( AssertionError e ) { error =
