7: catch( AssertionError e ) {
7: catch( AssertionError e ) { error = null ;
7: catch( AssertionError e ) { error = e ;
7: catch( AssertionError e ) { error = error ;
7: catch( AssertionError e ) { error =
7: catch( final AssertionError e ) {
